<!DOCTYPE html>
<html>
<head>
	<title>APLICACION DEMO PHP openshift </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
		body {
			background-color: black;
			color: white;
			font-family: Arial, Helvetica, sans-serif;
			text-align: center;
			padding-top: 50px;
		}
		h1 {
			font-size: 50px;
			margin-bottom: 0;
		}
		p {
			font-size: 20px;
			margin-top: 10px;
		}
	</style>
</head>
<body>
	<h1>ARCHIVO INDEX.PHP REUTILIZABLE</h1>
	<p>EL METODO DE AUTENTICACION QUE SE ESTARA UTILIZANDO ES EL SIGUIENTE OAUTH-PROXY DE OPENSHIFT,
	ESTE CONTENEDOR NO CUENTA CON UNA DIRECION ROUTEABLE EXTERNA SE ESTA UTILIZANDO UN PROXY INTERNO A NIVEL DE CLUSTER EL CUAL EMITE LA FUNCION DE EXPONER EL SERVICIO
	SOBRE LA RUTA PRICIPAL PARA TENER ACCESO A ESTA APP ES NECESARIO QUE EL USUARIO ESTE LOGEADO EN LA CONSOLA DE OPENSHIFT POR LO QUE SE PROVICIONO UN GRUPO LLAMADO CSN Y 3 USUARIOS 
	USUARIO1/2/3 LOS CUALES TIENEN ACCESO RESTRINGIDO SOLO A LAS APPS DEL NAMESAPCE LLAMADO CSN EN EL CUAL SE ESTA IMPLEMENTANDO ESTA DEMO
	EN ESTA DEMO SE ESTA IMPLEMENTADO UN ESQUEMA DEVOPS MUY SIMPLE EN EL CUAL UTILIZANDO SOLO 2 DE LOS MUCHOS COMPLEMENTOS Y FUNCIONALIZADES CON LAS QUE CUENTA OPENSHIFTH 
	EL CODIGO CON EL CUAL SE ESTA IMPLEMEtertertNTANDO ESTA DEMO TANTO EL DASHBOARD COMO LAS SINGLE APP SE ENCUENTRAN EN GITHUB https://github.com/FourthKindSolutions/app1 https://github.com/FourthKindSolutions/dashboard
	LOS CUALES SON PRIVADOS Y SE ENCUENTRAN PROTEJIDOS POR UN TOKEN DE 64 CARACTERES INDEPEMDIENTE MENTE DE LA SEGUIRAD DE OPENSHIFT Y GITHUB CADA VEZ QUE SE REALIZA UN CAMBIO EN EL CODIGO Y CON EL WEBHOOK PRECONFIGURADO
	OPENSHIFT DETECTARA EL CAMBIO E INICIARA LA COMPILACION DEL NUEVO CONTENEDOR Y ELIMINANDO LOS RESIGUALES Y ALMACENANDO EN EL REGISTRY INTERNO LOS ARTEFACTOS</p>
<?php
echo gethostname();
?>	
</body>
</html>
